### PR TITLE
User List from Ajax

### PR DESCRIPTION
**Pull request by german-e-mas**
In this PR I fetch the user list using Ajax from `http://localhost:3000/api/users/`. Then, they are listed as `user-elements`.

The auto property from iron-ajax specifies that the request is made whether the url or params change. [Link to API](https://www.webcomponents.org/element/PolymerElements/iron-ajax/iron-ajax#property-auto).

Here are some screenshots of the polymer server in action:
screencapture-localhost-8080-1492798764121

ptal @basicNew

### CODE REVIEW

**Comment by german-e-mas** [comment]
As we spoke last friday, I have removed the hardcoded user list, in order to show only the remote user list.

ptal @basicNew

**Comment by basicNew** [comment]
LGTM @german-e-mas !

**Comment by basicNew** [comment]
Btw, I think you can remove the property in `<h2>Hello [[prop1]]</h2>`, no need to make that dynamic

**Comment by german-e-mas** [comment]
Thanks @basicNew ! I'll push now the branch that includes the input element. Merging this one now.

**Comment by basicNew** [comment]
:+1:

**Pull request merged**
